# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
"""add version column to documents."""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "2372969158e3"
down_revision = '0b0b9288bacf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_documents_documents_file_id'), ['file_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_documents_tenants_tenant_id'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_tenants_tenant_id'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_documents_file_id'))
        batch_op.drop_column('version')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
    # ### end Alembic commands ###
